development:
  port: 30304
  rpc_host: localhost
  rpc_port: 8101
  minerthreads: 1
  genesis_block: config/genesis/dev_genesis.json
  datadir: /tmp/embark
  chains: config/chains/development.json
  mine_when_needed: true
  mine_periodically: false
  max_peers: 0
  gas_limit: 314159
  gas_price: 50000000000
  console: false
  whisper: true
  account:
    init: true
    password: config/password
production:
  rpc_host: localhost
  rpc_port: 8545
  datadir: default
  network_id: 1
  max_peers: 4
  console: true
  deploy_synchronously: true
  chains: config/chains/production.json
  gas_limit: 314159
  gas_price: 50000000000
  account:
    init: false
    address: dc99b79555385ab2fe0ff28c3c954a07b28aac5e
    password: config/password
